---
title: "Dashboard - NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("rest_inspec")
```

```{r}
nyc_inspections = rest_inspec %>%
  separate(inspection_date, into = c("year", "month", "day")) %>% 
  filter(as.numeric(year) == 2017) %>% 
  select(boro, camis, critical_flag, cuisine_description, year, month, score, zipcode) %>% drop_na()
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - Average Inspection Score Per Zip Code in Manhattan (Scatterplot)

```{r}
nyc_inspections %>% 
  filter(boro == "MANHATTAN") %>% 
  group_by(zipcode) %>% 
  mutate(average_score = mean(score),
         zipcode = as.factor(zipcode),
         text_label = str_c("Average Score: ", average_score, "\nZip Code: ",
         zipcode, "\nStatus: ", critical_flag)) %>% 
  plot_ly(y = ~average_score, x = ~ zipcode, color = ~critical_flag, text = ~text_label, type = "scatter", mode = "markers")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - Inspection Scores by Borough (Boxplot)

```{r}
nyc_inspections %>% 
  mutate(boro= fct_reorder(boro, score)) %>%
  plot_ly(x =~boro, y = ~score, type = "box", color = ~boro, colors = "viridis")
```

### Chart C - Inspection Scores by Month (Bar Graph)

```{r}
nyc_inspections %>% 
  group_by(month) %>% 
  mutate(
    max_score = max(score),
    text_label = str_c("Month: ", month, "\nScore: ", max_score)) %>%
  plot_ly(x =~month, y = ~score, type = "bar", text = ~text_label, color = ~month, colors = "viridis") %>% 
  layout(
  yaxis = list(tickformat = ","))
```

